### ISSUE TITLE
Refreshing Log Meal page clears the MealDetail ViewComponent

### ISSUE THREAD

**Issue by stringly** [emsmith8/MacroNewt#36]
If you are on "step 2" of the "Log Meal" process and refresh the browser, the MealDetail ViewComponent is cleared and the food items the user selected on the previous step are lost.

**Comment by emsmith8** [comment]
Handled with onbeforeunload function to warn user that leaving will cause them to lose logging process. Function is removed once meal is confirmed to allow them to move elsewhere without a warning message.

**Comment by emsmith8** [comment]
onbeforeunload doesn't work on mobile (primary target). Need to reconsider, maybe using pagehide event

**Comment by emsmith8** [comment]
pagehide wasn't working either, so took a different approach. Before, if the user refreshed the page while on the MealDetails or MealReview view it would reload the Logger Index page but without the foodSearch view component because the url parameters (i.e. #MealDetails) were preventing a clean reload. Now, when user refreshes during logging process there is a check to see if they were on either of the aforementioned pages. If so, redirected to the Logger Index with a clean slate.
